### ISSUE TITLE
BERNI

### ISSUE THREAD

**Issue by sebastianjaciel** [bemh1997/Proyecto-de-estructura-de-datos-IPN#1]
BERNA NO ME DEJA EDITAR AYUDA

**Comment by RodrigoFloresAltamirano** [comment]
sorry bro can't help you

**Comment by sebastianjaciel** [comment]
thanks men, gracias invezil

**Comment by sebastianjaciel** [comment]
tankhs bro, gracias invezil (por si no sabes frances)

**Comment by bemh1997** [comment]
Cada que uno guarda el documento se debe recargar el status y volver a subir tu info. :)
