### ISSUE TITLE
Asesoria profe Norman

### ISSUE THREAD

**Issue by bemh1997** [bemh1997/Proyecto-de-estructura-de-datos-IPN#2]
Estoy en asesoria con el profe Norma y esta viendo que no hemos avanzado.

Es un commit de prueba no se asusten.
@

**Comment by bemh1997** [comment]
Comenten en este issue . El ultimo en comentar que cierre el Issue
@norman-ipn @DanCruzV @sebastianjaciel @BrayanFG @RodrigoFloresAltamirano

**Comment by norman-ipn** [comment]
Tres dias y no han cerrado el issue? @DanCruzV @sebastianjaciel @BrayanFG @RodrigoFloresAltamirano

**Comment by DanCruzV** [comment]
Vale

**Comment by sebastianjaciel** [comment]
Asies
